### ISSUE TITLE
Tkinter issue!

### ISSUE THREAD

**Issue by enthogenesis** [third-eye-cyborg/KeywordApplication#1]
Thank you it's Intriguing but I think tkinter's being called twice (from a stackoverflow post)

When run from my terminal: python 3.8.5 (default, Jul 21 2020, 10:48:26)  OSX:

```
    Traceback (most recent call last):
     File "ggl_trend_subl.py", line 59, in <module>
       MyKeywordApp()
     File "ggl_trend_subl.py", line 12, in __init__
       self.newWindow()
      File "ggl_trend_subl.py", line 22, in newWindow
        p1 = PhotoImage(file='logo_image.png')
      File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/tkinter/__init__.py", line               4061, in __init__
         Image.__init__(self, 'photo', name, cnf, master, **kw)
       File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/tkinter/__init__.py", line  4006, in __init__
    self.tk.call(('image', 'create', imgtype, name,) + options)
_tkinter.TclError: couldn't recognize data in image file "logo_image.png"
```
Or  in a jupyter notebook with identical code... I typed it out & didn't work then I copy pasted your code but same diff:
```
---------------------------------------------------------------------------
TclError                                  Traceback (most recent call last)
<ipython-input-16-10ca7c4deff0> in <module>
     50 
     51 # call class
---> 52 MyKeywordApp()

<ipython-input-16-10ca7c4deff0> in __init__(self)
      3     def __init__(self):
      4 
----> 5         self.newWindow()
      6 
      7     def newWindow(self):

<ipython-input-16-10ca7c4deff0> in newWindow(self)
     14         # add logo image
     15         p1 = PhotoImage(file='logo_image.png')
---> 16         root.iconphoto(False, p1)
     17 
     18         # add labels

~/opt/anaconda3/lib/python3.7/tkinter/__init__.py in wm_iconphoto(self, default, *args)
   1908             self.tk.call('wm', 'iconphoto', self._w, "-default", *args)
   1909         else:
-> 1910             self.tk.call('wm', 'iconphoto', self._w, *args)
   1911     iconphoto = wm_iconphoto
   1912     def wm_iconposition(self, x=None, y=None):

TclError: can't use "pyimage5" as iconphoto: not a photo image
```

Would love love to get it working!

**Comment by third-eye-cyborg** [comment]
So, if you are using this code with Jupyter Notebooks you have to do a couple of things first. You have to open your Jupyter Notebook in the right directory. So, before you open it, go to the directory you have you image file in: 
`C:\Users\UserName\PycharmProjects\KeywordApplication`. Copy the absolute path to the directory to your clipboard. Then open up the Anaconda PowerShell. Once it loads up type in `cd 'your directory path'`. This will change your Anaconda directory to the folder where your image is located inside of. you can type `dir` and click _Enter_ on your keyboard and this will list the files contained, make sure you see the image file you need. Then while still in that directory type `jupyter notebooks` and click enter. This should load Jupyter Notebooks into your browser. Select new file and then you should be able to access all the files within the directory you started the Notebook in. 
<img width="673" alt="TestImage" src="https://user-images.githubusercontent.com/71515337/95110927-9ca7e300-06f3-11eb-84bc-65ba1eccb433.png">



As with the _`tkinter`_ issues. I will link a couple of resources that may help:
[https://stackoverflow.com/questions/47357090/tkinter-error-couldnt-recognize-data-in-image-file](https://stackoverflow.com/questions/47357090/tkinter-error-couldnt-recognize-data-in-image-file)
[https://www.geeksforgeeks.org/iconphoto-method-in-tkinter-python/](https://www.geeksforgeeks.org/iconphoto-method-in-tkinter-python/)

I hope this helps. Let me know!

**Comment by enthogenesis** [comment]
Hi there Dan,

Thanks so much for your reply and suggestions.

Actually, yes I had your png file in the same directory for jupyter  and I'm on OSX BTW.

After looking at your kindly provided stackoverflow posts, I tried a few things and eventually changed **logo_image.png** to **logo_image.gif** and it almost worked.... saw the tkninter window pop up... yes! but it just got stuck at the last pd.ExcelWriter() step:

`Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/tkinter/__init__.py", line 1883, in __call__
    return self.func(*args)
  File "ggl_trend_subl.py", line 45, in excelWriter
    writer = pd.ExcelWriter('keywords.xlsx')
  File "/usr/local/lib/python3.8/site-packages/pandas/io/excel/_openpyxl.py", line 18, in __init__
    from openpyxl.workbook import Workbook`

so that was missing in my system:

`pip3 install openpyxl `

and rant it again and entered 'cat' in the 'Input a Keyword':

`                 title                                          type
0                  Cat                                        Animal
1  Computed tomography                               Medical imaging
2     Caterpillar Inc.  Construction machinery and equipment company
3            Catamaran                                         Topic
4  Catalytic converter                                         Topic`

woohoo! & the .xlsx file is there filled with that info...  yeas!

Caveats: 

1. I still can't close out the program with control C, I have to delete python out of memory to kill it.. needs a tweak there?

3. Even though it works from command line....  in jupyter it's the same problem even with the .gif;

---------------------------------------------------------------------------
```
TclError                                  Traceback (most recent call last)
<ipython-input-43-dfccb128aacc> in <module>
     51 
     52 # call class
---> 53 MyKeywordApp()

<ipython-input-43-dfccb128aacc> in __init__(self)
      3     def __init__(self):
      4 
----> 5         self.newWindow()
      6 
      7     def newWindow(self):

<ipython-input-43-dfccb128aacc> in newWindow(self)
     15         p1 = PhotoImage(file='logo_image.gif')
     16         #p1 = ImageTk.PhotoImage(PilImage.open('logo_image.jpg').convert("RGB"))
---> 17         root.iconphoto(False, p1)
     18 
     19         # add labels

~/opt/anaconda3/lib/python3.7/tkinter/__init__.py in wm_iconphoto(self, default, *args)
   1908             self.tk.call('wm', 'iconphoto', self._w, "-default", *args)
   1909         else:
-> 1910             self.tk.call('wm', 'iconphoto', self._w, *args)
   1911     iconphoto = wm_iconphoto
   1912     def wm_iconposition(self, x=None, y=None):

TclError: can't use "pyimage10" as iconphoto: not a photo image

```
but I'll leave that for some other intrepid soul...  thanks again for the code ! Peace!
